import Mathlib.Tactic

/-!
# One conformal compensator can set both the gravitational scale and fermion masses

In four dimensions, under a constant Weyl rescaling `g -> Omega^2 g`, the standard weights
are schematically

    volume            : Omega^4,
    fermion bilinear  : Omega^-3,
    scalar compensator: Omega^-1,
    curvature R       : Omega^-2.

Therefore a fixed fermion mass density scales as `Omega` and breaks scale invariance, while

    sqrt(-g) * phi * psibar psi

and

    sqrt(-g) * phi^2 * R

are scale neutral.  Once `phi` takes a nonzero value, the same order parameter can set

    m_f      = y phi,
    M_Pl^2   = xi phi^2.

The gravity scale is even under `phi -> -phi`, while the signed fermion mass/phase is odd;
the physical mass magnitude is even.  This gives a minimal symmetry architecture in which
a scale-free boundary `phi=0` can be followed by simultaneous emergence of gravitational
and Compton scales.

This file proves only the algebraic scaling and parity statements.  It does not claim that
the Standard Model Higgs is this compensator, that the metric must vanish at `phi=0`, or
that a cosmological solution dynamically passes through such a point.
-/

namespace GppConformalMassScaleCompensator

/-- Weyl factor of a fixed mass density: volume `Omega^4` times fermion bilinear
    `Omega^-3`. -/
def fixedMassDensityScale (Omega : ℝ) : ℝ := Omega^4 / Omega^3

/-- Weyl factor after supplying one weight-minus-one scalar compensator. -/
def yukawaDensityScale (Omega : ℝ) : ℝ := Omega^4 / (Omega * Omega^3)

/-- Weyl factor of `sqrt(-g) phi^2 R`. -/
def gravityDensityScale (Omega : ℝ) : ℝ := Omega^4 / (Omega^2 * Omega^2)

/-- A fixed nonzero mass introduces one net power of the Weyl scale. -/
theorem fixed_mass_breaks_constant_Weyl (Omega : ℝ) (hO : Omega ≠ 0) :
    fixedMassDensityScale Omega = Omega := by
  simp [fixedMassDensityScale]
  field_simp [hO]
  ring

/-- The scalar-compensated Yukawa density is Weyl neutral. -/
theorem yukawa_compensator_restores_scale_invariance
    (Omega : ℝ) (hO : Omega ≠ 0) :
    yukawaDensityScale Omega = 1 := by
  simp [yukawaDensityScale]
  field_simp [hO]

/-- The scalar-compensated gravitational density is likewise Weyl neutral. -/
theorem gravity_compensator_scale_invariant
    (Omega : ℝ) (hO : Omega ≠ 0) :
    gravityDensityScale Omega = 1 := by
  simp [gravityDensityScale]
  field_simp [hO]

/-- Signed fermion mass generated by the scale field. -/
def fermionSignedMass (y phi : ℝ) : ℝ := y*phi

/-- Positive/branch-blind mass magnitude. -/
def fermionMassMagnitude (y phi : ℝ) : ℝ := |y*phi|

/-- Effective Planck-mass squared generated by the same scale field. -/
def planckMassSq (xi phi : ℝ) : ℝ := xi*phi^2

/-- Reversing the signed scale field reverses the oriented fermion mass/phase. -/
theorem phi_flip_reverses_signed_fermion_mass (y phi : ℝ) :
    fermionSignedMass y (-phi) = -fermionSignedMass y phi := by
  ring

/-- But the physical mass magnitude is blind to the branch sign. -/
theorem phi_flip_preserves_mass_magnitude (y phi : ℝ) :
    fermionMassMagnitude y (-phi) = fermionMassMagnitude y phi := by
  simp [fermionMassMagnitude]

/-- The gravitational scale is also branch blind. -/
theorem phi_flip_preserves_planck_scale (xi phi : ℝ) :
    planckMassSq xi (-phi) = planckMassSq xi phi := by
  simp [planckMassSq]

/-- At the symmetric point both generated scales vanish. -/
theorem zero_compensator_is_massless_scalefree (y xi : ℝ) :
    fermionSignedMass y 0 = 0 ∧
    fermionMassMagnitude y 0 = 0 ∧
    planckMassSq xi 0 = 0 := by
  simp [fermionSignedMass, fermionMassMagnitude, planckMassSq]

/-- A nonzero compensator and nonzero couplings turn on both scales. -/
theorem nonzero_compensator_turns_on_scales
    (y xi phi : ℝ) (hy : y ≠ 0) (hxi : xi ≠ 0) (hphi : phi ≠ 0) :
    fermionSignedMass y phi ≠ 0 ∧ planckMassSq xi phi ≠ 0 := by
  constructor
  · exact mul_ne_zero hy hphi
  · exact mul_ne_zero hxi (pow_ne_zero 2 hphi)

/-- Core parity package: the same `phi -> -phi` is odd in the fermionic first-order scale
    but even in the gravitational/quadratic scale. -/
theorem odd_fermion_even_gravity_package (y xi phi : ℝ) :
    fermionSignedMass y (-phi) = -fermionSignedMass y phi ∧
    fermionMassMagnitude y (-phi) = fermionMassMagnitude y phi ∧
    planckMassSq xi (-phi) = planckMassSq xi phi := by
  exact ⟨phi_flip_reverses_signed_fermion_mass y phi,
    phi_flip_preserves_mass_magnitude y phi,
    phi_flip_preserves_planck_scale xi phi⟩

end GppConformalMassScaleCompensator
