import Mathlib.NumberTheory.Zsqrtd.GaussianInt
import Mathlib.Data.Matrix.Mul
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.LinearAlgebra.Matrix.ConjTranspose

/-!
# The exact finite core of *Which Way Is Forward?*

Source: `Which_Way_Is_Forward_v26.tex` (Daniel Toupin, 22 September 2026), §"One time axis, two
microscopic orientations, and the four-lift carrier" and its subsections
`subsec:Drealform`, `subsec:Dsignature`, `subsec:halffliprealform`, together with the paper's
own check script `verify_which_way_is_forward.py`. Every statement here is a finite matrix
identity over the Gaussian integers `ℤ[i]`, checked by the kernel (`decide`). Nothing is
floating point and nothing is sampled.

## What is proved

* **The split-Clifford carrier** (`clifford_relations`). Four explicit `4 × 4` matrices
  `γ₀ = X⊗1, γ₁ = Z⊗1, γ₂ = J⊗X, γ₃ = J⊗Z` satisfy `γ_μγ_ν + γ_νγ_μ = 2η_{μν}` with
  `η = diag(1, 1, −1, −1)`: a real representation of `Cl(2,2)`.
* **The orientation algebra** (`orientation_algebra`). `a = γ₀γ₁`, `b = γ₂γ₃`, `c = γ₁γ₃`
  satisfy `a² = b² = −1`, `c² = 1`, `ab = ba`, `ca = −ac`, `cb = −bc`. With `χ = −ab`,
  `χ` is minus the volume element, and the temporal half flip is `r_t = r_q c`.
* **The unitary four-lift intertwiner** (`intertwiner_unitary`, `intertwiner`). An explicit
  `S` (here `2S`, to stay in `ℤ[i]`) with `S†S = 1` carries `a, b, c, r_q, r_t, χ` to the
  label-basis operators `I_q = diag(i,i,−i,−i)`, `I_t = diag(i,−i,i,−i)`, the reversal `D`,
  the half flips `R_q, R_t`, and `−I_qI_t`.
* **The carrier group** (`carrier_*`). The group generated by `I_q, I_t, D` has exactly 16
  elements; 11 of them square to `1` without being `1`, 4 square to `−1`; its center is
  `{±1, ±χ}`, and `D` is not central.
* **The real form** (`fixD_iff`, `halfFlips_agree_on_fixD`, `Rt_reverses_chi`). `D v = v` iff
  `v = (a, b, b, a)`; on that fixed space the two half flips coincide; `R_t` reverses `χ`, so it
  is not the central deck sign `−1`.
* **The Minkowski realization** (`minkowski_realization`). The *same* `a, b, c` also live in a
  `Cl(3,1)` representation, as one bivector and two trivectors.

## What is not here

The paper's physical readings (orientation labels as charge and time arrows, `D` as a real
structure on field space, the Compton clock) are dictionary statements; this file proves the
algebra they are read from and nothing more. The paper's other exact claims — the
coordinate-blade signature scan, the `Spin(6,2)`/`Spin(10,2)` charge-conjugation signs, the
determinant cover — are not formalized here.

## Relation to `codex/orientation-mass-time-formalization`

The paper's Lean inventory lists 34 modules on that branch (draft PR #173). As of 2026-09-26
the branch does not build (69 modules fail), and none of its modules states the explicit
`Cl(2,2)` intertwiner or the order-16 carrier. This file is independent of that branch and
overlaps none of its modules.
-/

namespace GppOrientationCliffordCore

open Matrix

/-- Gaussian integers `ℤ[i]`: every entry below lives here. -/
abbrev K := GaussianInt

/-- `4 × 4` matrices over `ℤ[i]`. -/
abbrev M := Matrix (Fin 4) (Fin 4) K

/-- The imaginary unit of `ℤ[i]`. -/
def ii : K := ⟨0, 1⟩

/-! ## The split-Clifford carrier -/

/-- `γ₀ = X ⊗ 1`. -/
def g0 : M := !![0, 0, 1, 0; 0, 0, 0, 1; 1, 0, 0, 0; 0, 1, 0, 0]
/-- `γ₁ = Z ⊗ 1`. -/
def g1 : M := !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, -1, 0; 0, 0, 0, -1]
/-- `γ₂ = J ⊗ X`, with `J = [[0,1],[−1,0]]`. -/
def g2 : M := !![0, 0, 0, 1; 0, 0, 1, 0; 0, -1, 0, 0; -1, 0, 0, 0]
/-- `γ₃ = J ⊗ Z`. -/
def g3 : M := !![0, 0, 1, 0; 0, 0, 0, -1; -1, 0, 0, 0; 0, 1, 0, 0]

/-- The four generators, indexed. -/
def gamma : Fin 4 → M := ![g0, g1, g2, g3]

/-- The split metric `η = diag(1, 1, −1, −1)`. -/
def eta : Fin 4 → K := ![1, 1, -1, -1]

/-- **`Cl(2,2)`:** `γ_μγ_ν + γ_νγ_μ = 2η_{μν}·1`. -/
theorem clifford_relations (μ ν : Fin 4) :
    gamma μ * gamma ν + gamma ν * gamma μ = if μ = ν then (2 * eta μ) • (1 : M) else 0 := by
  revert μ ν; decide

/-! ## The orientation algebra -/

/-- `a = γ₀γ₁`. -/
def a : M := g0 * g1
/-- `b = γ₂γ₃`. -/
def b : M := g2 * g3
/-- `c = γ₁γ₃`. -/
def c : M := g1 * g3
/-- The charge half flip `r_q = γ₀`. -/
def rq : M := g0
/-- The temporal half flip `r_t = γ₀γ₁γ₃`. -/
def rt : M := g0 * g1 * g3
/-- The relative orientation `χ = −ab`. -/
def chi : M := -(a * b)

/-- **The orientation algebra:** two commuting complex structures `a, b` and a real
involution `c` anticommuting with both. -/
theorem orientation_algebra :
    a * a = -1 ∧ b * b = -1 ∧ c * c = 1 ∧ a * b = b * a ∧
      c * a = -(a * c) ∧ c * b = -(b * c) := by
  decide

/-- `χ` is minus the volume element `γ₀γ₁γ₂γ₃`. -/
theorem chi_eq_neg_volume : chi = -(g0 * g1 * g2 * g3) := by decide

/-- The temporal half flip is the charge half flip followed by the real structure. -/
theorem rt_eq_rq_mul_c : rt = rq * c := by decide

/-! ## The label basis and the unitary intertwiner -/

/-- `I_q = diag(i, i, −i, −i)`. -/
def Iq : M := !![ii, 0, 0, 0; 0, ii, 0, 0; 0, 0, -ii, 0; 0, 0, 0, -ii]
/-- `I_t = diag(i, −i, i, −i)`. -/
def It : M := !![ii, 0, 0, 0; 0, -ii, 0, 0; 0, 0, ii, 0; 0, 0, 0, -ii]
/-- The diagonal reversal `D`, sending lift `(q, t)` to `(−q, −t)`. -/
def D : M := !![0, 0, 0, 1; 0, 0, 1, 0; 0, 1, 0, 0; 1, 0, 0, 0]
/-- The charge half flip in the label basis, `(q, t) ↦ (−q, t)`. -/
def Rq : M := !![0, 0, 1, 0; 0, 0, 0, 1; 1, 0, 0, 0; 0, 1, 0, 0]
/-- The temporal half flip in the label basis, `(q, t) ↦ (q, −t)`. -/
def Rt : M := !![0, 1, 0, 0; 1, 0, 0, 0; 0, 0, 0, 1; 0, 0, 1, 0]
/-- `χ` in the label basis: `−I_qI_t = diag(1, −1, −1, 1)`, the product `q·t`. -/
def chiL : M := -(Iq * It)

/-- `2S`, where `S` is the paper's eigenbasis matrix. Its columns are
`α_q (u_q ⊗ w_t)` for `(q,t) = (1,1), (1,−1), (−1,1), (−1,−1)`, with `u_q = (1, −iq)/√2`,
`w_t = (1, it)/√2`, `α_1 = 1`, `α_{−1} = −i`; doubling clears the `1/2`. -/
def S2 : M := !![1, 1, -ii, -ii; ii, -ii, 1, -1; -ii, -ii, 1, 1; 1, -1, ii, -ii]

/-- **`S` is unitary:** `(2S)†(2S) = 4`. -/
theorem intertwiner_unitary : S2ᴴ * S2 = (4 : K) • (1 : M) := by decide

/-- **The intertwiner.** `S` carries the Clifford operators to the label-basis operators:
`X S = S X_label` for each pair, which with unitarity is `S† X S = X_label`. -/
theorem intertwiner :
    a * S2 = S2 * Iq ∧ b * S2 = S2 * It ∧ c * S2 = S2 * D ∧
      rq * S2 = S2 * Rq ∧ rt * S2 = S2 * Rt ∧ chi * S2 = S2 * chiL := by
  decide

/-- **The four-lift algebra**, in the label basis: `D` anticommutes with both complex
structures and commutes with `χ`. -/
theorem fourLift_algebra :
    D * Iq = -(Iq * D) ∧ D * It = -(It * D) ∧ D * chiL = chiL * D ∧ D * D = 1 := by
  decide

/-! ## The carrier group -/

/-- The 16 elements of the group generated by `I_q, I_t, D`: `{±1, ±I_q, ±I_t, ±χ}` and the
same eight times `D`. -/
def carrier : List M :=
  let base : List M := [1, -1, Iq, -Iq, It, -It, chiL, -chiL]
  base ++ base.map (· * D)

theorem carrier_length : carrier.length = 16 := rfl

/-- The 16 listed matrices are distinct. -/
theorem carrier_nodup : carrier.Nodup := by decide

/-- The generators lie in the carrier. -/
theorem gens_mem_carrier : Iq ∈ carrier ∧ It ∈ carrier ∧ D ∈ carrier := by decide

/-- **The carrier is closed under multiplication.** With `1 ∈ carrier` and finiteness, it is
a group, and it is the group generated by `I_q, I_t, D` (see `carrier_mem_closure`). -/
theorem carrier_mul_mem : ∀ g ∈ carrier, ∀ h ∈ carrier, g * h ∈ carrier := by decide

theorem one_mem_carrier : (1 : M) ∈ carrier := by decide

/-- Every carrier element is a product of generators, so the carrier is exactly the
submonoid they generate. -/
theorem carrier_mem_closure :
    ∀ g ∈ carrier, g ∈ Submonoid.closure ({Iq, It, D} : Set M) := by
  have hq : Iq ∈ Submonoid.closure ({Iq, It, D} : Set M) := Submonoid.subset_closure (by simp)
  have ht : It ∈ Submonoid.closure ({Iq, It, D} : Set M) := Submonoid.subset_closure (by simp)
  have hd : D ∈ Submonoid.closure ({Iq, It, D} : Set M) := Submonoid.subset_closure (by simp)
  have e1 : (-1 : M) = Iq * Iq := by decide
  have e2 : -Iq = Iq * Iq * Iq := by decide
  have e3 : -It = It * It * It := by decide
  have e4 : chiL = Iq * Iq * Iq * It := by decide
  have e5 : -chiL = Iq * It := by decide
  have base : ∀ g ∈ ([1, -1, Iq, -Iq, It, -It, chiL, -chiL] : List M),
      g ∈ Submonoid.closure ({Iq, It, D} : Set M) := by
    intro g hg
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hg
    rcases hg with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
    · exact Submonoid.one_mem _
    · rw [e1]; exact Submonoid.mul_mem _ hq hq
    · exact hq
    · rw [e2]; exact Submonoid.mul_mem _ (Submonoid.mul_mem _ hq hq) hq
    · exact ht
    · rw [e3]; exact Submonoid.mul_mem _ (Submonoid.mul_mem _ ht ht) ht
    · rw [e4]
      exact Submonoid.mul_mem _ (Submonoid.mul_mem _ (Submonoid.mul_mem _ hq hq) hq) ht
    · rw [e5]; exact Submonoid.mul_mem _ hq ht
  intro g hg
  simp only [carrier, List.mem_append, List.mem_map] at hg
  rcases hg with hg | ⟨h, hh, rfl⟩
  · exact base g hg
  · exact Submonoid.mul_mem _ (base h hh) hd

/-- **The carrier is exactly the monoid generated by `I_q, I_t, D`** (which, being finite, is
the group they generate). With `carrier_nodup`, this group has order 16. -/
theorem closure_eq_carrier :
    (Submonoid.closure ({Iq, It, D} : Set M) : Set M) = {g | g ∈ carrier} := by
  let S : Submonoid M :=
    { carrier := {g | g ∈ carrier}
      mul_mem' := fun {g h} hg hh => carrier_mul_mem g hg h hh
      one_mem' := one_mem_carrier }
  apply Set.Subset.antisymm
  · have hle : Submonoid.closure ({Iq, It, D} : Set M) ≤ S := by
      rw [Submonoid.closure_le]
      intro g hg
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
      rcases hg with rfl | rfl | rfl
      · exact gens_mem_carrier.1
      · exact gens_mem_carrier.2.1
      · exact gens_mem_carrier.2.2
    exact hle
  · exact carrier_mem_closure

/-- **Order statistics:** besides the identity, exactly 11 elements square to `1` (order 2)
and exactly 4 square to `−1` (order 4). -/
theorem carrier_order_counts :
    (carrier.filter fun g => g ≠ 1 ∧ g * g = 1).length = 11 ∧
      (carrier.filter fun g => g * g = -1).length = 4 := by
  decide

/-- **The center is `{±1, ±χ}`.** -/
theorem carrier_center :
    ∀ g ∈ carrier, (∀ h ∈ carrier, g * h = h * g) ↔ g ∈ ([1, -1, chiL, -chiL] : List M) := by
  decide

/-- `D` is not central: it does not commute with `I_q`. -/
theorem D_not_central : D * Iq ≠ Iq * D := by decide

/-! ## The real form and the half flips -/

/-- **`Fix(D) = {(a, b, b, a)}`.** -/
theorem fixD_iff (v : Fin 4 → K) : D *ᵥ v = v ↔ v 0 = v 3 ∧ v 1 = v 2 := by
  simp only [D, Matrix.cons_mulVec, Matrix.empty_mulVec, dotProduct, Fin.sum_univ_four]
  constructor
  · intro h
    have h0 := congrFun h 0
    have h1 := congrFun h 1
    simp at h0 h1
    exact ⟨h0.symm, h1.symm⟩
  · rintro ⟨h03, h12⟩
    funext i
    fin_cases i <;> simp [h03, h12]

/-- **On the real form the two half flips coincide.** -/
theorem halfFlips_agree_on_fixD (v : Fin 4 → K) (hv : D *ᵥ v = v) : Rq *ᵥ v = Rt *ᵥ v := by
  obtain ⟨h03, h12⟩ := (fixD_iff v).mp hv
  funext i
  fin_cases i <;>
    simp [Rq, Rt, Matrix.cons_mulVec, Matrix.empty_mulVec, dotProduct, Fin.sum_univ_four, h03,
      h12]

/-- **`R_t` reverses `χ`**, so it is not central and in particular is not the deck sign `−1`. -/
theorem Rt_reverses_chi : Rt * chiL * Rt = -chiL ∧ Rt ≠ -1 := by decide

/-! ## The same algebra inside `Cl(3,1)` -/

/-- `Γ₃ = J ⊗ J`. -/
def h2 : M := !![0, 0, 0, 1; 0, 0, -1, 0; 0, -1, 0, 0; 1, 0, 0, 0]

/-- The `Cl(3,1)` generators `Γ = (X⊗1, Z⊗1, J⊗J, J⊗X)`, metric `(1, 1, 1, −1)`. -/
def gammaM : Fin 4 → M := ![g0, g1, h2, g2]

/-- The Minkowski metric `diag(1, 1, 1, −1)`. -/
def etaM : Fin 4 → K := ![1, 1, 1, -1]

theorem minkowski_clifford_relations (μ ν : Fin 4) :
    gammaM μ * gammaM ν + gammaM ν * gammaM μ =
      if μ = ν then (2 * etaM μ) • (1 : M) else 0 := by
  revert μ ν; decide

/-- **Minkowski realization.** The same `a, b, c` are `Γ₁Γ₂`, `Γ₁Γ₂Γ₃`, `−Γ₁Γ₃Γ₄` in
`Cl(3,1)`: one bivector and two trivectors. -/
theorem minkowski_realization :
    a = g0 * g1 ∧ b = g0 * g1 * h2 ∧ c = -(g0 * h2 * g2) := by
  decide

end GppOrientationCliffordCore
