import Mathlib.Tactic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import GppVerify.StandardModel.PatiSalamHypercharge

/-!
# Low-prime Cartan geometry: A3 -> A2 and the Pati-Salam X generator

This module records finite exact algebra associated with the low-prime path

  2 -- 3 -- 5 -- 7

when the first edge is the unique prime gap 1 and the final two edges are the
overlapping gap-2 pair.

The oriented incidence columns have Gram matrix equal to the Cartan matrix A3.
Deleting the p=2 vertex / first edge leaves the 3--5--7 incidence with Gram
matrix A2.  In the ordered vertex basis (2,3,5,7), the unique trace-zero
diagonal shape that is constant on the last three coordinates is proportional
to (-3,1,1,1), i.e. X = 3(B-L).

These are finite arithmetic and matrix identities.  The physical identification
with SU(4)_c -> SU(3)_c x U(1)_{B-L} is a dictionary hypothesis, not proved here.
-/

namespace GppPrimePatiSalam

/-- Incidence matrix of the oriented path 2 -> 3 -> 5 -> 7. -/
def boundaryIncidence : Matrix (Fin 4) (Fin 3) ℤ :=
  !![1, 0, 0;
     -1, 1, 0;
      0,-1, 1;
      0, 0,-1]

/-- Cartan matrix of type A3. -/
def cartanA3 : Matrix (Fin 3) (Fin 3) ℤ :=
  !![2,-1, 0;
     -1,2,-1;
      0,-1,2]

/-- The low-prime path incidence Gram is exactly the A3 Cartan matrix. -/
theorem boundary_incidence_gram :
    boundaryIncidence.transpose * boundaryIncidence = cartanA3 := by
  native_decide

/-- Incidence matrix of the gap-two color candidate 3 -> 5 -> 7. -/
def colorIncidence : Matrix (Fin 3) (Fin 2) ℤ :=
  !![1, 0;
     -1, 1;
      0,-1]

/-- Cartan matrix of type A2. -/
def cartanA2 : Matrix (Fin 2) (Fin 2) ℤ :=
  !![2,-1;
     -1,2]

/-- The 3--5--7 gap-two incidence Gram is exactly the A2 Cartan matrix. -/
theorem color_incidence_gram :
    colorIncidence.transpose * colorIncidence = cartanA2 := by
  native_decide

/-- The A3 and A2 Cartan determinants are 4 and 3 respectively. -/
theorem cartan_determinants :
    cartanA3.det = 4 ∧ cartanA2.det = 3 := by
  native_decide

/-- X=3(B-L) in the ordered basis (lepton, color1, color2, color3). -/
def xBL : Fin 4 → ℤ := ![-3, 1, 1, 1]

theorem xBL_values :
    xBL 0 = -3 ∧ xBL 1 = 1 ∧ xBL 2 = 1 ∧ xBL 3 = 1 := by
  native_decide

/-- X is trace-free, as required for an su(4) Cartan generator. -/
theorem xBL_trace_zero :
    xBL 0 + xBL 1 + xBL 2 + xBL 3 = 0 := by
  native_decide

/-- X annihilates the two color simple roots. -/
theorem xBL_color_roots_zero :
    xBL 1 - xBL 2 = 0 ∧ xBL 2 - xBL 3 = 0 := by
  native_decide

/-- The lepton-color simple root has X-charge -4 in this orientation. -/
theorem xBL_leptoquark_root :
    xBL 0 - xBL 1 = -4 := by
  native_decide

/-- Any trace-zero diagonal integer generator constant on the three color
coordinates has shape (-3k,k,k,k). -/
theorem color_centralizer_shape
    (x0 x1 x2 x3 : ℤ)
    (h12 : x1 = x2) (h23 : x2 = x3)
    (htr : x0 + x1 + x2 + x3 = 0) :
    x0 = -3 * x1 ∧ x2 = x1 ∧ x3 = x1 := by
  omega

/-- Adjoint branching dimension count 15 = 8 + 1 + 3 + 3. -/
theorem su4_adjoint_branching_dimension :
    (15 : ℕ) = 8 + 1 + 3 + 3 := by
  norm_num

/-- First color simple-root raising matrix E_(3,5) in the ordered
(2,3,5,7) basis. -/
def E12 : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0,0,0,0;
     0,0,1,0;
     0,0,0,0;
     0,0,0,0]

/-- Second color simple-root raising matrix E_(5,7). -/
def E23 : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0,0,0,0;
     0,0,0,0;
     0,0,0,1;
     0,0,0,0]

/-- Composite color root E_(3,7). -/
def E13 : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0,0,0,0;
     0,0,0,1;
     0,0,0,0;
     0,0,0,0]

/-- The missing direct 3--7 transition is generated by the commutator of the
two gap-two simple-root transitions. -/
theorem color_composite_root :
    E12 * E23 - E23 * E12 = E13 := by
  native_decide

/-- Gap-one lepton-to-first-color simple-root raising matrix E_(2,3). -/
def E01 : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0,1,0,0;
     0,0,0,0;
     0,0,0,0;
     0,0,0,0]

/-- Generated lepton-to-second-color transition E_(2,5). -/
def E02 : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0,0,1,0;
     0,0,0,0;
     0,0,0,0;
     0,0,0,0]

/-- Generated lepton-to-third-color transition E_(2,7). -/
def E03 : Matrix (Fin 4) (Fin 4) ℤ :=
  !![0,0,0,1;
     0,0,0,0;
     0,0,0,0;
     0,0,0,0]

/-- The unique gap-one root plus the first color root generates the second
lepton-color root. -/
theorem leptoquark_second_color :
    E01 * E12 - E12 * E01 = E02 := by
  native_decide

/-- Continuing the Lie closure generates the third lepton-color root. -/
theorem leptoquark_third_color :
    E02 * E23 - E23 * E02 = E03 := by
  native_decide

/-- The verified Pati-Salam hypercharge normalization maps X=-3, T3R=0
to the left-lepton hypercharge -1/2. -/
theorem lepton_hypercharge_from_prime_X :
    GppPatiSalamHypercharge.hypercharge (xBL 0) 0 = -(1 : ℚ) / 2 := by
  norm_num [xBL, GppPatiSalamHypercharge.hypercharge]

/-- The same normalization maps X=+1, T3R=0 to the left-quark
hypercharge +1/6. -/
theorem quark_hypercharge_from_prime_X :
    GppPatiSalamHypercharge.hypercharge (xBL 1) 0 = (1 : ℚ) / 6 := by
  norm_num [xBL, GppPatiSalamHypercharge.hypercharge]


/-- Block Cartan matrix A3 + A1 + A1, the root-system type of
SU(4) x SU(2) x SU(2). -/
def patiSalamCartan : Matrix (Fin 5) (Fin 5) ℤ :=
  !![2,-1, 0, 0, 0;
     -1,2,-1, 0, 0;
      0,-1,2, 0, 0;
      0, 0,0, 2, 0;
      0, 0,0, 0, 2]

/-- The determinant factors as det(A3)*det(A1)^2 = 4*2*2 = 16. -/
theorem pati_salam_cartan_det :
    patiSalamCartan.det = 16 := by
  native_decide

/-- The defining-carrier dimensions selected by the initial prime components
are 4,2,2, hence one Pati-Salam chiral family has 4*2 + 4*2 = 16 slots. -/
theorem one_family_slot_count :
    (4 : ℕ) * 2 + 4 * 2 = 16 := by
  norm_num


/-- Incidence matrix of the two disjoint twin pairs 11--13 and 17--19. -/
def weakPrimeIncidence : Matrix (Fin 4) (Fin 2) ℤ :=
  !![ 1, 0;
     -1, 0;
      0, 1;
      0,-1]

/-- The post-color prime quadruplet has D2 = A1 + A1 Cartan Gram. -/
theorem weak_prime_incidence_gram :
    weakPrimeIncidence.transpose * weakPrimeIncidence =
      !![(2 : ℤ),0;0,2] := by
  native_decide

/-- The selected eight-prime carrier
(2,3,5,7,11,13,17,19) with five simple incidence roots. -/
def primePatiSalamIncidence : Matrix (Fin 8) (Fin 5) ℤ :=
  !![ 1, 0, 0, 0, 0;
     -1, 1, 0, 0, 0;
      0,-1, 1, 0, 0;
      0, 0,-1, 0, 0;
      0, 0, 0, 1, 0;
      0, 0, 0,-1, 0;
      0, 0, 0, 0, 1;
      0, 0, 0, 0,-1]

/-- The full selected prime incidence Gram is exactly the Pati-Salam
A3 + A1 + A1 Cartan matrix. -/
theorem prime_pati_salam_incidence_gram :
    primePatiSalamIncidence.transpose * primePatiSalamIncidence =
      patiSalamCartan := by
  native_decide

end GppPrimePatiSalam

#print axioms GppPrimePatiSalam.boundary_incidence_gram
#print axioms GppPrimePatiSalam.color_incidence_gram
#print axioms GppPrimePatiSalam.color_centralizer_shape
#print axioms GppPrimePatiSalam.color_composite_root
#print axioms GppPrimePatiSalam.lepton_hypercharge_from_prime_X
