import Mathlib.Tactic
import GppVerify.StandardModel.FourOrientationGaugeProjection

/-!
# Relational matter selection rule

Let `chi` be the relational matter grading on the four-lift carrier.  Any evolution or
interaction map `F` which commutes with `chi` preserves the matter (`chi=+1`) and
antimatter (`chi=-1`) sectors separately.  Conversely, the microscopic half flips
anticommute with `chi` and exchange the two sectors.

This makes the cosmological question exact.  Starting from a pure relational-matter state,
an anti-aligned `+-/-+` excitation cannot be generated by a `chi`-even dynamics.  It
requires a `chi`-odd interaction/defect or a many-body process in which the total relational
charge is compensated elsewhere.

No claim is made here that the Standard Model Hamiltonian exactly conserves this proposed
`chi`; identifying the physical symmetry which would enforce the commutator is the next
field-theoretic task.
-/

namespace GppRelationalMatterSelectionRule

open GppFourOrientationGaugeProjection

/-- Any map commuting with `chi` preserves the relational-matter eigenspace. -/
theorem commuting_map_preserves_matter
    (F : Orientation4 → Orientation4)
    (hcomm : ∀ v, chi (F v) = F (chi v))
    (v : Orientation4) (hv : chi v = v) :
    chi (F v) = F v := by
  rw [hcomm, hv]

/-- The same commuting map preserves the relational-antimatter eigenspace. -/
theorem commuting_map_preserves_antimatter
    (F : Orientation4 → Orientation4)
    (hcomm : ∀ v, chi (F v) = F (chi v))
    (v : Orientation4) (hv : chi v = -v)
    (hneg : F (-v) = -(F v)) :
    chi (F v) = -(F v) := by
  rw [hcomm, hv, hneg]

/-- A charge-orientation half flip anticommutes with the relational grading. -/
theorem charge_half_flip_anticommutes_chi (v : Orientation4) :
    chi (chargeFlip v) = - chargeFlip (chi v) := by
  rcases v with ⟨a,b,c,d⟩
  simp [chi, chargeFlip]

/-- A microscopic temporal half flip also anticommutes with the relational grading. -/
theorem temporal_half_flip_anticommutes_chi (v : Orientation4) :
    chi (temporalFlip v) = - temporalFlip (chi v) := by
  rcases v with ⟨a,b,c,d⟩
  simp [chi, temporalFlip]

/-- Consequently either half flip takes any matter eigenstate to the antimatter eigenspace. -/
theorem half_flips_exchange_matter_sector
    (v : Orientation4) (hv : chi v = v) :
    chi (chargeFlip v) = -chargeFlip v ∧
    chi (temporalFlip v) = -temporalFlip v := by
  constructor
  · rw [charge_half_flip_anticommutes_chi, hv]
  · rw [temporal_half_flip_anticommutes_chi, hv]

/-- The full diagonal reversal is `chi`-even and therefore cannot itself turn matter into
    antimatter. -/
theorem diagonal_flip_preserves_relational_sector (v : Orientation4) :
    chi (diagReverse v) = diagReverse (chi v) := by
  exact (diag_commutes_chi v).symm

/-- Concrete cosmological selection rule: if an evolution commutes with `chi`, a pure
    matter lift cannot evolve into the canonical pure antimatter lift. -/
theorem chi_even_dynamics_cannot_map_matter_to_antimatter
    (F : Orientation4 → Orientation4)
    (hcomm : ∀ v, chi (F v) = F (chi v))
    (hF : F matterLift = antimatterLift) : False := by
  have hm : chi (F matterLift) = F matterLift :=
    commuting_map_preserves_matter F hcomm matterLift chi_matter
  rw [hF, chi_antimatter] at hm
  have hzero : antimatterLift = (0 : Orientation4) := by
    have := congrArg (fun v : Orientation4 => v.2.1) hm
    norm_num [antimatterLift] at this ⊢
  have hc := congrArg (fun v : Orientation4 => v.2.1) hzero
  norm_num [antimatterLift] at hc

end GppRelationalMatterSelectionRule
