import Mathlib.Tactic

/-!
# Relative complex orientation: abstract symmetry theorem

The charged-Kähler/CAR construction has two complex structures `I,J` and a relative grading

    Q = - I J.

The transformation law of Q follows PURELY ALGEBRAICALLY from which of I and J a discrete
operation reverses.  This file removes all dependence on the earlier 2x2 toy matrices.

For any associative ring of operators:

* a one-orientation flip that anticommutes with I and commutes with J anticommutes with Q;
* the complementary half flip, commuting with I and anticommuting with J, also anticommutes
  with Q;
* a diagonal reversal that anticommutes with BOTH I and J commutes with Q;
* an operation commuting with both I and J also commutes with Q.

Thus "physical sign = relative alignment" is a general operator identity, not a peculiarity
of a chosen representation.  In charged CAR, charge reversal realizes the first case and
time reversal realizes the diagonal case (with anti-linearity handled on the underlying real
carrier).
-/

namespace GppRelativeComplexOrientationSymmetryTheorem

variable {A : Type*} [Ring A]

/-- Relative grading generated by two orientation operators. -/
def relativeQ (I J : A) : A := -(I * J)

/-- Flipping only I reverses the relative grading. -/
theorem first_orientation_flip_anticommutes_Q
    (I J C : A)
    (hCI : C * I = -(I * C))
    (hCJ : C * J = J * C) :
    C * relativeQ I J = -(relativeQ I J * C) := by
  simp only [relativeQ]
  calc
    C * (-(I * J)) = -(C * I * J) := by noncomm_ring
    _ = -((-(I * C)) * J) := by rw [hCI]
    _ = I * C * J := by noncomm_ring
    _ = I * (J * C) := by rw [hCJ]; simp [mul_assoc]
    _ = -((-(I * J)) * C) := by noncomm_ring

/-- Flipping only J reverses the same relative grading. -/
theorem second_orientation_flip_anticommutes_Q
    (I J F : A)
    (hFI : F * I = I * F)
    (hFJ : F * J = -(J * F)) :
    F * relativeQ I J = -(relativeQ I J * F) := by
  simp only [relativeQ]
  calc
    F * (-(I * J)) = -(F * I * J) := by noncomm_ring
    _ = -(I * F * J) := by rw [hFI]
    _ = -(I * (-(J * F))) := by rw [hFJ]; simp [mul_assoc]
    _ = -((-(I * J)) * F) := by noncomm_ring

/-- Simultaneously flipping BOTH complex orientations preserves their relative grading. -/
theorem diagonal_orientation_flip_commutes_Q
    (I J T : A)
    (hTI : T * I = -(I * T))
    (hTJ : T * J = -(J * T)) :
    T * relativeQ I J = relativeQ I J * T := by
  simp only [relativeQ]
  calc
    T * (-(I * J)) = -(T * I * J) := by noncomm_ring
    _ = -((-(I * T)) * J) := by rw [hTI]
    _ = I * T * J := by noncomm_ring
    _ = I * (-(J * T)) := by rw [hTJ]; simp [mul_assoc]
    _ = (-(I * J)) * T := by noncomm_ring

/-- An operation preserving both absolute orientations preserves the relative grading too. -/
theorem preserve_both_commutes_Q
    (I J U : A)
    (hUI : U * I = I * U)
    (hUJ : U * J = J * U) :
    U * relativeQ I J = relativeQ I J * U := by
  simp only [relativeQ]
  calc
    U * (-(I * J)) = -(U * I * J) := by noncomm_ring
    _ = -(I * U * J) := by rw [hUI]
    _ = -(I * (J * U)) := by rw [hUJ]; simp [mul_assoc]
    _ = (-(I * J)) * U := by noncomm_ring

/-- Capstone: the relative grading records the PARITY of the number of orientation reversals:
    odd number of flips reverses Q, even number preserves Q. -/
theorem relative_orientation_parity_capstone
    (I J C F T : A)
    (hCI : C * I = -(I * C)) (hCJ : C * J = J * C)
    (hFI : F * I = I * F) (hFJ : F * J = -(J * F))
    (hTI : T * I = -(I * T)) (hTJ : T * J = -(J * T)) :
    C * relativeQ I J = -(relativeQ I J * C) ∧
    F * relativeQ I J = -(relativeQ I J * F) ∧
    T * relativeQ I J = relativeQ I J * T := by
  exact ⟨first_orientation_flip_anticommutes_Q I J C hCI hCJ,
    second_orientation_flip_anticommutes_Q I J F hFI hFJ,
    diagonal_orientation_flip_commutes_Q I J T hTI hTJ⟩

end GppRelativeComplexOrientationSymmetryTheorem
