import Mathlib.Tactic

/-!
# Weyl-invariant Compton phase: the scale field and proper time occur only as a product

Suppose the pre-metric/scale-free theory has local Weyl redundancy.  Under a positive Weyl
factor `Omega`, let

    ds  -> Omega ds,
    phi -> phi/Omega,

where `phi` is a weight-minus-one scale compensator.  If a fermion mass is generated by

    m = y phi,

then `m -> m/Omega`.  The dimensionless Compton phase increment

    dtheta = (m c^2 / hbar) ds

is exactly Weyl invariant because the two scale factors cancel.

This gives a precise mathematical version of the project's phrase "mass is time": neither
`m` nor a metric proper-time interval `ds` is separately invariant in a Weyl-symmetric
phase, but their product is.  When `phi=0`, the generated mass and intrinsic Compton phase
vanish.  When `phi != 0`, fixing the Weyl gauge by setting `phi` to a constant simultaneously
fixes the mass scale and the proper-time ruler.

This is an algebraic Weyl-covariance theorem.  It does not prove that the primordial universe
was Weyl invariant or that the Standard-Model Higgs is the compensator.
-/

namespace GppWeylInvariantComptonClock

/-- Weyl-rescaled proper-time/length increment for positive `Omega`. -/
def rescaledInterval (Omega ds : ℝ) : ℝ := Omega * ds

/-- Weight-minus-one scale compensator. -/
def rescaledCompensator (Omega phi : ℝ) : ℝ := phi / Omega

/-- Yukawa-generated signed mass. -/
def generatedMass (y phi : ℝ) : ℝ := y*phi

/-- Dimensionless Compton phase increment, suppressing only no constants. -/
def comptonPhaseIncrement (m c hbar ds : ℝ) : ℝ :=
  (m*c^2/hbar) * ds

/-- A weight-minus-one generated mass rescales inversely. -/
theorem generatedMass_Weyl_weight_minus_one
    (Omega y phi : ℝ) (hO : Omega ≠ 0) :
    generatedMass y (rescaledCompensator Omega phi) =
      generatedMass y phi / Omega := by
  simp [generatedMass, rescaledCompensator]
  field_simp [hO]
  ring

/-- The mass-times-interval product is exactly Weyl invariant. -/
theorem mass_times_interval_Weyl_invariant
    (Omega y phi ds : ℝ) (hO : Omega ≠ 0) :
    generatedMass y (rescaledCompensator Omega phi) *
        rescaledInterval Omega ds =
      generatedMass y phi * ds := by
  simp [generatedMass, rescaledCompensator, rescaledInterval]
  field_simp [hO]
  ring

/-- Therefore the full Compton phase increment is Weyl invariant as well. -/
theorem compton_phase_Weyl_invariant
    (Omega y phi c hbar ds : ℝ)
    (hO : Omega ≠ 0) (hh : hbar ≠ 0) :
    comptonPhaseIncrement
        (generatedMass y (rescaledCompensator Omega phi)) c hbar
        (rescaledInterval Omega ds) =
      comptonPhaseIncrement (generatedMass y phi) c hbar ds := by
  simp [comptonPhaseIncrement, generatedMass, rescaledCompensator,
    rescaledInterval]
  field_simp [hO, hh]
  ring

/-- At the symmetric zero-compensator point there is no generated Compton phase. -/
theorem zero_compensator_zero_intrinsic_phase (y c hbar ds : ℝ) :
    comptonPhaseIncrement (generatedMass y 0) c hbar ds = 0 := by
  simp [comptonPhaseIncrement, generatedMass]

/-- Any nonzero compensator can be Weyl-rescaled to a chosen positive reference magnitude,
    provided the two have the same sign.  This is the scalar core of choosing Einstein/
    clock gauge. -/
theorem gauge_fix_positive_compensator
    (phi phi0 : ℝ) (hphi : 0 < phi) (hphi0 : 0 < phi0) :
    ∃ Omega : ℝ, 0 < Omega ∧ rescaledCompensator Omega phi = phi0 := by
  refine ⟨phi/phi0, div_pos hphi hphi0, ?_⟩
  simp [rescaledCompensator]
  field_simp [ne_of_gt hphi, ne_of_gt hphi0]

/-- Once the compensator is fixed to `phi0`, the generated mass is fixed to `y phi0`. -/
theorem clock_gauge_fixes_mass (y phi0 : ℝ) :
    generatedMass y phi0 = y*phi0 := rfl

end GppWeylInvariantComptonClock
