import Mathlib.Tactic
import GppVerify.StandardModel.FourLiftHaarPeterWeyl

/-!
# The common Z2 quotient of the cyclic and four-lift order-four carriers

Two different order-four groups occur in the orientation program:

* the cyclic quarter-turn carrier Z4, generated by an element tau with tau^2 central;
* the Klein four carrier V4=Z2×Z2 of the independent q and t signs.

They are not isomorphic.  What is canonically comparable after the orientation dictionary
has selected the diagonal deck element D in V4 is the quotient:

    Z4 / <tau^2>  ~= Z2,
    V4 / <D>      ~= Z2.

Important: V4 has THREE nontrivial order-two elements.  D is distinguished by the named
factorization into q and t and by simultaneous reversal, not by the abstract group
structure alone.

This file formalizes the finite quotient maps directly.
-/

namespace GppZ4V4CommonQuotient

open GppFourLiftHaarPeterWeyl

abbrev Z4Label := Fin 4

/-- Add the central half-turn: k -> k+2 mod 4. -/
def z4HalfTurn (k : Z4Label) : Z4Label :=
  ⟨(k.val + 2) % 4, by omega⟩

/-- The quotient Z4/<2> remembers only parity of the quarter-turn exponent. -/
def z4QuotientBit (k : Z4Label) : Bool :=
  if k.val % 2 = 0 then false else true

/-- The V4/<D> quotient is the relative-alignment bit q xor t. -/
def v4QuotientBit (x : V4) : Bool := Bool.xor x.1 x.2

theorem z4HalfTurn_sq (k : Z4Label) :
    z4HalfTurn (z4HalfTurn k) = k := by
  fin_cases k <;> rfl

/-- The Z4 quotient bit is unchanged by the central half-turn. -/
theorem z4QuotientBit_halfTurn (k : Z4Label) :
    z4QuotientBit (z4HalfTurn k) = z4QuotientBit k := by
  fin_cases k <;> decide

/-- The V4 quotient bit is unchanged by simultaneous reversal D. -/
theorem v4QuotientBit_deckD (x : V4) :
    v4QuotientBit (deckD x) = v4QuotientBit x := by
  rcases x with ⟨q,t⟩
  cases q <;> cases t <;> rfl

/-- Both quotient bits are onto the same two-element target. -/
theorem both_quotients_surjective :
    (∃ k0 k1 : Z4Label,
      z4QuotientBit k0 = false ∧ z4QuotientBit k1 = true) ∧
    (∃ x0 x1 : V4,
      v4QuotientBit x0 = false ∧ v4QuotientBit x1 = true) := by
  constructor
  · refine ⟨0,1,?_,?_⟩ <;> decide
  · refine ⟨(false,false),(false,true),rfl,rfl⟩

/-- The two Z4 fibers are exactly {0,2} and {1,3}. -/
theorem z4_fibers (k : Z4Label) :
    (z4QuotientBit k = false ↔ k = 0 ∨ k = 2) ∧
    (z4QuotientBit k = true  ↔ k = 1 ∨ k = 3) := by
  fin_cases k <;> decide

/-- The two V4 fibers are aligned and anti-aligned sign pairs. -/
theorem v4_fibers (x : V4) :
    (v4QuotientBit x = false ↔ x.1 = x.2) ∧
    (v4QuotientBit x = true  ↔ x.1 ≠ x.2) := by
  rcases x with ⟨q,t⟩
  cases q <;> cases t <;> decide

/--
Capstone: although the order-four carriers are different, their selected order-two
quotients have the same two-valued structure.
-/
theorem common_binary_quotient :
    (∀ k, z4QuotientBit (z4HalfTurn k) = z4QuotientBit k) ∧
    (∀ x, v4QuotientBit (deckD x) = v4QuotientBit x) ∧
    (z4QuotientBit 0 = v4QuotientBit (false,false)) ∧
    (z4QuotientBit 1 = v4QuotientBit (false,true)) := by
  refine ⟨z4QuotientBit_halfTurn, v4QuotientBit_deckD, ?_, ?_⟩ <;> decide

end GppZ4V4CommonQuotient

#print axioms GppZ4V4CommonQuotient.common_binary_quotient
