import Mathlib.NumberTheory.ArithmeticFunction.VonMangoldt

/-!
# Logarithmic Dirichlet derivation and the Möbius gauge identity

Let

  (D f)(n) = log(n) f(n).

Because `log(ab)=log a + log b`, `D` is a derivation for Dirichlet convolution.  Applying
Möbius inversion to the zeta-synthesized derivative therefore gives

  mu * D(zeta * f) = D f + Lambda * f.

Thus the von Mangoldt channel is exactly the connection term generated by conjugating
logarithmic length through zeta synthesis.  This is a pure arithmetic identity; no RH
assumption enters.
-/

namespace GppDirichletLogGaugeIdentity

open Finset Nat ArithmeticFunction
open scoped ArithmeticFunction ArithmeticFunction.vonMangoldt zeta Moebius

/-- Logarithmic length differentiation on arithmetic functions. -/
noncomputable def lengthDeriv (f : ArithmeticFunction ℝ) : ArithmeticFunction ℝ :=
  ⟨fun n => Real.log n * f n, by simp⟩

@[simp] theorem lengthDeriv_apply (f : ArithmeticFunction ℝ) (n : ℕ) :
    lengthDeriv f n = Real.log n * f n := rfl

/-- Logarithmic length is a derivation of Dirichlet convolution. -/
theorem lengthDeriv_mul (f g : ArithmeticFunction ℝ) :
    lengthDeriv (f * g) = lengthDeriv f * g + f * lengthDeriv g := by
  ext n
  rcases eq_or_ne n 0 with rfl | hn
  · simp [lengthDeriv]
  · simp only [lengthDeriv_apply, ArithmeticFunction.mul_apply,
      ArithmeticFunction.add_apply]
    rw [Finset.mul_sum, ← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl
    intro p hp
    have hprod : p.1 * p.2 = n := (Nat.mem_divisorsAntidiagonal.mp hp).1
    have ⟨hp1, hp2⟩ := Nat.ne_zero_of_mem_divisorsAntidiagonal hp
    rw [← hprod, Nat.cast_mul,
      Real.log_mul (by exact_mod_cast hp1) (by exact_mod_cast hp2)]
    ring

/-- Differentiating the arithmetic zeta element gives the logarithmic arithmetic function. -/
theorem lengthDeriv_zeta :
    lengthDeriv (ζ : ArithmeticFunction ℝ) = ArithmeticFunction.log := by
  ext n
  rcases eq_or_ne n 0 with rfl | hn
  · simp [lengthDeriv]
  · simp [lengthDeriv, ArithmeticFunction.log_apply,
      ArithmeticFunction.zeta_apply_ne hn]

/--
**Exact Möbius gauge identity.**  Conjugating logarithmic differentiation by zeta synthesis
produces the von Mangoldt connection term.
-/
theorem mobius_lengthDeriv_zeta_mul
    (f : ArithmeticFunction ℝ) :
    (μ : ArithmeticFunction ℝ) * lengthDeriv ((ζ : ArithmeticFunction ℝ) * f) =
      lengthDeriv f + (Λ : ArithmeticFunction ℝ) * f := by
  rw [lengthDeriv_mul]
  rw [mul_add, ← mul_assoc, ← mul_assoc]
  rw [lengthDeriv_zeta]
  simp
  ac_rfl

/-- Equivalent connection form after subtracting the bare logarithmic derivative. -/
theorem mobius_gauge_connection
    (f : ArithmeticFunction ℝ) :
    (μ : ArithmeticFunction ℝ) * lengthDeriv ((ζ : ArithmeticFunction ℝ) * f)
      - lengthDeriv f =
      (Λ : ArithmeticFunction ℝ) * f := by
  rw [mobius_lengthDeriv_zeta_mul]
  abel

end GppDirichletLogGaugeIdentity
