import Mathlib.Tactic

/-!
# Finite fermionic spectral moment Gram identity

This file formalizes the finite algebra behind the proposed positive Fredholm determinant
route to RH.

For nonnegative one-particle eigenvalues `lambda_r`, define the signed-BPY-style moment
sequence

  mu_k = 2 * sum_r lambda_r^(k+1).

Then every finite Hankel quadratic form is exactly a sum of Hilbert squares:

  sum_{i,j} c_i c_j mu_(i+j)
    = 2 * sum_r lambda_r * (sum_i c_i lambda_r^i)^2 >= 0.

This is the finite spectral version of

  mu_k = 2 Tr(A^(k+1)),

for a positive operator `A`, and of the Hilbert--Schmidt Gram factorization

  mu_(i+j) = 2 <A^(i+1/2), A^(j+1/2)>_HS.

No zeta-zero input and no infinite-dimensional trace-class claim is made here.
-/

namespace GppFiniteFermionicMomentGram

open Finset

/-- Finite positive spectral moment sequence. -/
def moment {n : ℕ} (lam : Fin n → ℝ) (k : ℕ) : ℝ :=
  2 * ∑ r : Fin n, lam r ^ (k + 1)

/-- Polynomial source evaluated at one spectral value. -/
def polyEval {m : ℕ} (c : Fin m → ℝ) (x : ℝ) : ℝ :=
  ∑ i : Fin m, c i * x ^ (i : ℕ)

/-- The Hankel quadratic form generated by the finite spectral moments. -/
def hankelQuad {n m : ℕ} (lam : Fin n → ℝ) (c : Fin m → ℝ) : ℝ :=
  ∑ i : Fin m, ∑ j : Fin m, c i * c j * moment lam ((i : ℕ) + (j : ℕ))

/-- Pointwise spectral square identity. -/
theorem pointwise_square_identity {m : ℕ}
    (c : Fin m → ℝ) (x : ℝ) :
    (∑ i : Fin m, ∑ j : Fin m,
        c i * c j * x ^ ((i : ℕ) + (j : ℕ) + 1))
      = x * (polyEval c x)^2 := by
  simp only [polyEval, pow_add, pow_succ]
  rw [sq]
  simp_rw [Finset.sum_mul, Finset.mul_sum]
  ring

/-- Exact finite Hankel = sum-of-squares factorization. -/
theorem hankelQuad_eq_sum_squares {n m : ℕ}
    (lam : Fin n → ℝ) (c : Fin m → ℝ) :
    hankelQuad lam c
      = 2 * ∑ r : Fin n, lam r * (polyEval c (lam r))^2 := by
  unfold hankelQuad moment
  simp_rw [Finset.mul_sum]
  rw [Finset.mul_sum]
  simp_rw [← Finset.sum_mul]
  -- Reorder the finite sums so each spectral value is treated pointwise.
  calc
    ∑ i : Fin m, ∑ j : Fin m,
        c i * c j * (2 * ∑ r : Fin n, lam r ^ ((i : ℕ) + (j : ℕ) + 1))
        = 2 * ∑ r : Fin n,
            ∑ i : Fin m, ∑ j : Fin m,
              c i * c j * lam r ^ ((i : ℕ) + (j : ℕ) + 1) := by
                simp_rw [Finset.mul_sum, Finset.sum_mul]
                rw [Finset.sum_comm]
                congr 1
                funext r
                rw [Finset.sum_comm]
                ring
    _ = 2 * ∑ r : Fin n, lam r * (polyEval c (lam r))^2 := by
          congr 1
          apply Finset.sum_congr rfl
          intro r hr
          rw [pointwise_square_identity]

/-- Positivity of every finite Hankel form for a nonnegative spectrum. -/
theorem hankelQuad_nonneg {n m : ℕ}
    (lam : Fin n → ℝ) (hlam : ∀ r, 0 ≤ lam r)
    (c : Fin m → ℝ) :
    0 ≤ hankelQuad lam c := by
  rw [hankelQuad_eq_sum_squares]
  positivity

/-- Strict positivity when at least one occupied spectral channel sees a nonzero source. -/
theorem hankelQuad_pos_of_channel {n m : ℕ}
    (lam : Fin n → ℝ) (hlam : ∀ r, 0 ≤ lam r)
    (c : Fin m → ℝ)
    (r0 : Fin n) (hr0 : 0 < lam r0)
    (hc0 : polyEval c (lam r0) ≠ 0) :
    0 < hankelQuad lam c := by
  rw [hankelQuad_eq_sum_squares]
  have hnonneg : ∀ r : Fin n, 0 ≤ lam r * (polyEval c (lam r))^2 := by
    intro r
    positivity
  have hpos : 0 < lam r0 * (polyEval c (lam r0))^2 := by
    have hs : 0 < (polyEval c (lam r0))^2 := sq_pos_of_ne_zero hc0
    positivity
  have hsum : 0 < ∑ r : Fin n, lam r * (polyEval c (lam r))^2 := by
    exact Finset.sum_pos' (fun r hr => hnonneg r) ⟨r0, Finset.mem_univ _, hpos⟩
  positivity

end GppFiniteFermionicMomentGram
