import Mathlib.NumberTheory.ArithmeticFunction.VonMangoldt
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# Möbius gauge connection and the von Mangoldt channel

The prime-power weight in the explicit formula is not an independent arithmetic object.
In the Dirichlet-convolution algebra it is produced exactly by applying the Möbius inverse
of the zeta element to the logarithmic length function:

  mu * log = Lambda.

Equivalently,

  Lambda * zeta = log.

This file packages that standard Mathlib identity in the form used by the GPP operator
program and records the half-density twist `Lambda(n)/sqrt(n)` appearing in the Weil
prime channel.

The finite/infinite operator interpretation is a dictionary:
`mu * log = Lambda` is the scalar incidence-algebra core of the statement that the
von Mangoldt channel is the connection produced by gauging logarithmic length with
zeta synthesis.  No RH claim is made here.
-/

namespace GppMobiusVonMangoldtGaugeConnection

open ArithmeticFunction
open scoped ArithmeticFunction ArithmeticFunction.vonMangoldt zeta Moebius

/-- The Dirichlet-convolution connection one-form generated by Möbius inversion. -/
noncomputable def gaugePotential : ArithmeticFunction ℝ :=
  (μ : ArithmeticFunction ℝ) * ArithmeticFunction.log

/-- Exact arithmetic identity: the gauge potential is the von Mangoldt function. -/
theorem gaugePotential_eq_vonMangoldt :
    gaugePotential = ArithmeticFunction.vonMangoldt := by
  simp [gaugePotential]

/-- Pointwise version of the same identity. -/
theorem gaugePotential_apply (n : ℕ) :
    gaugePotential n = ArithmeticFunction.vonMangoldt n := by
  rw [gaugePotential_eq_vonMangoldt]

/-- Multiplying the connection back by the zeta element recovers logarithmic length. -/
theorem gaugePotential_mul_zeta :
    gaugePotential * (ζ : ArithmeticFunction ℝ) = ArithmeticFunction.log := by
  rw [gaugePotential_eq_vonMangoldt]
  simp

/-- The half-density prime-power weight used by the Weil explicit formula. -/
noncomputable def halfDensityWeight (n : ℕ) : ℝ :=
  ArithmeticFunction.vonMangoldt n / Real.sqrt n

/-- Every half-density von Mangoldt weight is nonnegative. -/
theorem halfDensityWeight_nonneg (n : ℕ) :
    0 ≤ halfDensityWeight n := by
  unfold halfDensityWeight
  exact div_nonneg vonMangoldt_nonneg (Real.sqrt_nonneg n)

/-- The weight vanishes at `n = 1`, as required for a prime-power boundary channel. -/
@[simp] theorem halfDensityWeight_one : halfDensityWeight 1 = 0 := by
  simp [halfDensityWeight]

/-- At a prime, the half-density weight is exactly `log p / sqrt p`. -/
theorem halfDensityWeight_prime {p : ℕ} (hp : p.Prime) :
    halfDensityWeight p = Real.log p / Real.sqrt p := by
  simp [halfDensityWeight, ArithmeticFunction.vonMangoldt_apply_prime hp]

/-- At every positive prime power the von Mangoldt numerator is inherited from the base prime. -/
theorem halfDensityWeight_prime_pow {p k : ℕ} (hp : p.Prime) (hk : k ≠ 0) :
    halfDensityWeight (p ^ k) =
      Real.log p / Real.sqrt (p ^ k) := by
  simp [halfDensityWeight, ArithmeticFunction.vonMangoldt_apply_pow hk,
    ArithmeticFunction.vonMangoldt_apply_prime hp]

end GppMobiusVonMangoldtGaugeConnection
