import Mathlib.Tactic
import GppVerify.CelestialHolography.InfinityLeviScreenGeometry

/-!
# Conformal infinity as a cone over the split celestial rank-one quadric

For the flat infinity point `I=(0,0,0,0,0,1)`, conformal infinity is the tangent
hyperplane section of the Klein quadric:

  p01 = 0,
  -p02*p13 + p03*p12 = 0.

The second equation says exactly that the four screen coordinates form a rank-one `2x2`
matrix.  Such a nonzero matrix factorizes projectively as `lambda tensor lambdatilde`,
so its projective null directions are the two spinor factors `RP1 x RP1`.

The remaining coordinate `p23` moves along the null line generated by `I` while leaving
the screen matrix fixed.  Thus, away from the cone vertex, the flat conformal boundary is
algebraically a family of generator lines labelled by the celestial rank-one quadric.

This module proves the coordinate cone/generator statements.  It does not introduce a
projective quotient type or separate future/past real components of conformal infinity.
-/

namespace GppConformalInfinityConeFactorization

open GppGrassmannianGooglyDecomposition
open GppKleinNullInfinityBoundary
open GppFlatInfinityCelestialFactorization
open GppInfinityLeviScreenGeometry

/-- Exact screen characterization of the flat conformal boundary. -/
theorem onConformalInfinity_iff_screen_null (p : P6) :
    OnConformalInfinity p ↔ p.p01 = 0 ∧ det2 (screen p) = 0 := by
  constructor
  · intro h
    have hp01 : p.p01 = 0 := (onConformalInfinity_iff p).mp h |>.2
    constructor
    · exact hp01
    · have hQ : kleinQ p = 0 := h.1
      have hs := kleinQ_on_infinity_hyperplane p hp01
      rw [hQ] at hs
      simp [screenQ] at hs
      linarith
  · rintro ⟨hp01,hdet⟩
    have hQ : kleinQ p = 0 := by
      rw [kleinQ_on_infinity_hyperplane p hp01]
      simp [screenQ, hdet]
    exact (onConformalInfinity_iff p).2 ⟨hQ,hp01⟩

/-- Every null screen matrix lifts to a conformal-infinity point, independently of the
coordinate along the generator. -/
theorem null_screenLift_on_conformalInfinity
    (A : M2) (r : ℝ) (hA : det2 A = 0) :
    OnConformalInfinity (screenLift A r) := by
  rw [onConformalInfinity_iff_screen_null]
  exact ⟨rfl, by simpa [screen_screenLift] using hA⟩

/-- In particular every rank-one celestial spinor outer product labels an entire
conformal-infinity generator. -/
theorem celestial_spinors_label_infinity_generator
    (lambda lambdatilde : Spinor2) (r : ℝ) :
    OnConformalInfinity
      (screenLift (nullMomentum lambda lambdatilde) r) := by
  apply null_screenLift_on_conformalInfinity
  exact nullMomentum_det_zero lambda lambdatilde

/-- Changing the generator coordinate is exactly a shift along the null infinity line. -/
theorem screenLift_generator_shift
    (A : M2) (r s : ℝ) :
    screenLift A r = shiftAlongInfinity (r-s) (screenLift A s) := by
  rcases A with ⟨a,b,c,d⟩
  apply P6.ext <;> simp [screenLift, shiftAlongInfinity] <;> ring

/-- All points on one generator have the same celestial screen label. -/
theorem generator_has_constant_screen
    (A : M2) (r s : ℝ) :
    screen (screenLift A r) = screen (screenLift A s) := by
  simp [screen_screenLift]

/-- Moving along a conformal-infinity generator preserves conformal infinity. -/
theorem conformalInfinity_generator_closed
    (p : P6) (hp : OnConformalInfinity p) (t : ℝ) :
    OnConformalInfinity (shiftAlongInfinity t p) := by
  have hp01 : p.p01 = 0 := (onConformalInfinity_iff_screen_null p).mp hp |>.1
  have hdet : det2 (screen p) = 0 := (onConformalInfinity_iff_screen_null p).mp hp |>.2
  rw [onConformalInfinity_iff_screen_null]
  constructor
  · simpa [shiftAlongInfinity] using hp01
  · rw [screen_shiftAlongInfinity]
    exact hdet

/-- The cone vertex itself has zero screen coordinates. -/
theorem infinity_vertex_screen_zero :
    screen infinityPoint = (0,0,0,0) := by
  rfl

/-- The cone vertex is the zero-screen lift with unit generator coordinate. -/
theorem infinityPoint_eq_zeroScreenLift :
    infinityPoint = screenLift (0,0,0,0) 1 := by
  rfl

/-- A nonzero rank-one screen remains null under the independent determinant-one left and
right actions; hence the two `SL(2)` factors act on the space of cone-generator labels. -/
theorem sl2_actions_preserve_generator_label_nullity
    (L R : M2) (hL : det2 L = 1) (hR : det2 R = 1)
    (lambda lambdatilde : Spinor2) :
    det2 (leftRightAct L R (nullMomentum lambda lambdatilde)) = 0 := by
  apply sl2_left_right_preserves_null L R (nullMomentum lambda lambdatilde) hL hR
  exact nullMomentum_det_zero lambda lambdatilde

end GppConformalInfinityConeFactorization
