import Mathlib.Tactic
import GppVerify.CelestialHolography.FourierDualSplitPolarity
import GppVerify.CelestialHolography.KleinSpinorIncidence
import GppVerify.CelestialHolography.SplitGooglyGeometryCapstone
import GppVerify.CelestialHolography.TwistorCanonicalShift
import GppVerify.CelestialHolography.TwistorRepresentationConvention

/-!
# Googly geometry intertwiner spine

This file packages the strongest exact finite-dimensional part of the GPP googly
construction currently available, with two newly explicit qualifications.

Starting from the support constraints produced by restricting the four-dimensional
Fourier phase to a twistor 2-plane, one obtains:

1. the ordinary annihilator plane in Fourier-dual space;
2. after CHOOSING the ambient bilinear form `diag(+,+,-,-)` to identify `V* -> V`,
   the corresponding split-polarity plane, up to the central projective sign;
3. after big-cell row reduction, the split Grassmannian complement `A^{-T}`;
4. in Plucker coordinates, the normalized Hodge-star image associated with that chosen
   metric plus orientation;
5. independently, ambient rank four gives the canonical degree reflection `k -> -k-4`.

The last integer reflection has two different tagged interpretations: cross-side full
Fourier `PT* <-> PT` preserves the physical helicity of the momentum state, whereas the
same degree reflection read on one fixed twistor side is the opposite-helicity bundle
degree.  These statements must not be conflated.

The new `KleinSpinorIncidence` module supplies the epsilon-only replacement for the
noncanonical pointwise polarity shortcut: a Klein bivector acts between `V` and `V*`
by the two chiral Clifford maps, with square `-Q_Klein`.  On the Klein quadric the action
is nilpotent and its two kernels are exactly the twistor line and annihilator dual-twistor
line of the same spacetime point.  Thus the intrinsic geometry is a chiral incidence
operator/correspondence, not an isomorphism `V* ≅ V`.

Accordingly the exact support geometry is more accurately

  D_Fourier-support -> D_annihilator,

while the epsilon-only common geometry is

  Klein point p -> [ cPlus(p): V -> V*, cMinus(p): V* -> V ],

with the chosen metric polarity retained only as an optional additional identification.

What is NOT proved here:

* the chosen ambient `diag(+,+,-,-)` polarity is generated by epsilon alone (it is not;
  `FourierDualSplitPolarity` gives an explicit `SL(4,R)` non-invariance witness);
* a conformally canonical pointwise identification `PT* -> PT`;
* the full homogeneous distributional/projective Fourier-Penrose integral theorem in Lean;
* a physical orientation reversal from the polarity map;
* generation of an independent second chiral component for nonlinear Einstein gravity.

These distinctions leave the incidence/Fourier results intact while isolating the real
remaining googly bridge.
-/

namespace GppGooglyGeometryIntertwinerSpine

open GppGrassmannianGooglyDecomposition
open GppFourierSliceSupportGeometry
open GppFourierDualSplitPolarity
open GppSplitPolarityComplementBridge
open GppSplitSignatureHodgeGrassmannian
open GppTwistorCanonicalShift
open GppTwistorWeightDuality
open GppTwistorRepresentationConvention

/-- Fourier support constraints become the chosen split metric polarity after the chosen
musical identification, up to the central projective sign. -/
theorem fourier_support_to_split_polarity
    (a b c d : ℝ) (ξ : GppTwistorAnnihilatorIncidence.V4)
    (h1 : phaseConstraint1 a b ξ = 0)
    (h2 : phaseConstraint2 c d ξ = 0) :
    splitSharp ξ =
      scaleV4 (-1)
        (splitDualLineVector a b c d ξ.2.2.1 ξ.2.2.2) :=
  fourier_support_sharp_is_projective_split_polarity a b c d ξ h1 h2

/-- The chosen split polarity row-reduces to the corresponding Hodge/Grassmannian
complement. -/
theorem split_polarity_to_grassmannian
    (a b c d : ℝ) (hD : a*d - b*c ≠ 0) :
    let A : M2 := (a,b,c,d)
    let B := splitComplement A
    splitReducedRow1 a b c d = (1,0,B.1,B.2.1) ∧
    splitReducedRow2 a b c d = (0,1,B.2.2.1,B.2.2.2) :=
  split_polarity_is_hodge_complement a b c d hD

/-- The Grassmannian complement is the normalized split Hodge-star image in Plucker
coordinates for the chosen metric/orientation data. -/
theorem grassmannian_to_split_hodge
    (A : M2) (hD : det2 A ≠ 0) :
    chartPlucker (splitComplement A) =
      let D := det2 A
      ⟨1, (splitStar (chartPlucker A)).p02 / D,
          (splitStar (chartPlucker A)).p03 / D,
          (splitStar (chartPlucker A)).p12 / D,
          (splitStar (chartPlucker A)).p13 / D,
          (splitStar (chartPlucker A)).p23 / D⟩ :=
  chartPlucker_splitComplement A hD

/-- Same-side numerical interpretation: the canonical degree reflection takes the degree
assigned on a fixed convention to `n` into the degree assigned there to `-n`.  This is
a bundle-degree statement, not the cross-side physical interpretation of full Fourier. -/
theorem ambient_four_to_opposite_helicity_degree_same_side (n : ℤ) :
    serreWeight (twistorWeight n) = twistorWeight (-n) :=
  serreWeight_is_helicityFlip n

/-- Backward-compatible name for the same numerical degree theorem.  The theorem is exact;
its name must not be read as saying that cross-side full Fourier flips the physical helicity. -/
theorem ambient_four_to_opposite_helicity (n : ℤ) :
    serreWeight (twistorWeight n) = twistorWeight (-n) :=
  ambient_four_to_opposite_helicity_degree_same_side n

/-- Cross-side physical interpretation: the same rank-four degree reflection maps the
dual-twistor representative to the ordinary-twistor representative with the SAME physical
helicity label. -/
theorem ambient_four_cross_side_same_helicity (n : ℤ) :
    fourierWeight (dualTwistorPhysicalWeight n) = ordinaryTwistorPhysicalWeight n :=
  fourier_dual_to_ordinary_same_helicity n

/-- Original finite-dimensional capstone, retained as an exact coordinate/degree theorem.
The final conjunct is explicitly the same-side numerical degree reading. -/
theorem finite_dimensional_googly_spine
    (a b c d : ℝ)
    (ξ : GppTwistorAnnihilatorIncidence.V4)
    (h1 : phaseConstraint1 a b ξ = 0)
    (h2 : phaseConstraint2 c d ξ = 0)
    (hD : a*d - b*c ≠ 0)
    (n : ℤ) :
    splitSharp ξ =
        scaleV4 (-1)
          (splitDualLineVector a b c d ξ.2.2.1 ξ.2.2.2) ∧
    (let A : M2 := (a,b,c,d)
     let B := splitComplement A
     splitReducedRow1 a b c d = (1,0,B.1,B.2.1) ∧
     splitReducedRow2 a b c d = (0,1,B.2.2.1,B.2.2.2)) ∧
    chartPlucker (splitComplement (a,b,c,d)) =
      (let D := det2 (a,b,c,d)
       ⟨1, (splitStar (chartPlucker (a,b,c,d))).p02 / D,
           (splitStar (chartPlucker (a,b,c,d))).p03 / D,
           (splitStar (chartPlucker (a,b,c,d))).p12 / D,
           (splitStar (chartPlucker (a,b,c,d))).p13 / D,
           (splitStar (chartPlucker (a,b,c,d))).p23 / D⟩) ∧
    serreWeight (twistorWeight n) = twistorWeight (-n) := by
  refine ⟨fourier_support_to_split_polarity a b c d ξ h1 h2, ?_, ?_, ?_⟩
  · exact split_polarity_to_grassmannian a b c d hD
  · exact grassmannian_to_split_hodge (a,b,c,d) hD
  · exact ambient_four_to_opposite_helicity_degree_same_side n

/-- Side-aware version of the capstone: the support/polarity/Hodge coordinate chain is
unchanged, while the actual cross-side Fourier degree theorem is recorded with its same
physical helicity label. -/
theorem finite_dimensional_googly_spine_side_aware
    (a b c d : ℝ)
    (ξ : GppTwistorAnnihilatorIncidence.V4)
    (h1 : phaseConstraint1 a b ξ = 0)
    (h2 : phaseConstraint2 c d ξ = 0)
    (hD : a*d - b*c ≠ 0)
    (n : ℤ) :
    splitSharp ξ =
        scaleV4 (-1)
          (splitDualLineVector a b c d ξ.2.2.1 ξ.2.2.2) ∧
    (let A : M2 := (a,b,c,d)
     let B := splitComplement A
     splitReducedRow1 a b c d = (1,0,B.1,B.2.1) ∧
     splitReducedRow2 a b c d = (0,1,B.2.2.1,B.2.2.2)) ∧
    chartPlucker (splitComplement (a,b,c,d)) =
      (let D := det2 (a,b,c,d)
       ⟨1, (splitStar (chartPlucker (a,b,c,d))).p02 / D,
           (splitStar (chartPlucker (a,b,c,d))).p03 / D,
           (splitStar (chartPlucker (a,b,c,d))).p12 / D,
           (splitStar (chartPlucker (a,b,c,d))).p13 / D,
           (splitStar (chartPlucker (a,b,c,d))).p23 / D⟩) ∧
    fourierWeight (dualTwistorPhysicalWeight n) = ordinaryTwistorPhysicalWeight n := by
  refine ⟨fourier_support_to_split_polarity a b c d ξ h1 h2, ?_, ?_, ?_⟩
  · exact split_polarity_to_grassmannian a b c d hD
  · exact grassmannian_to_split_hodge (a,b,c,d) hD
  · exact ambient_four_cross_side_same_helicity n

end GppGooglyGeometryIntertwinerSpine
